### PR TITLE
MVP PO

### PR DESCRIPTION
**Pull request by junsupark94**
@EtoKruto Product Overview module + server controllers.js and routes.js

### CODE REVIEW

**Comment by Lesson9** [comment]
@junsupark94 @itsjohnong @EtoKruto 

The code looks fine, but I'm thinking about whether it is necessary to modularize it one step further because we have 4 relatively-independent widgets/sections on the page. 

For example, in controller.js, we can group different controller functions by different sections:
- for Junsu: `module.exports.overview = {}` or multiple `module.exports.overview.xxx = {}`;
- for Alex: `module.exports.relatedItems = {}` or multiple `module.exports.relatedItems.xxx = {}`;
- for Spencer: `module.exports.qanda = {}` or multiple `module.exports.qanda.xxx = {}`;
- for John: `module.exports.reviews = {}` or multiple `module.exports.reviews.xxx = {}`;

Would like to know your opinions on this.

**Comment by junsupark94** [comment]
@Lesson9 Yeah, I agree with you. Mine was just an initial attempt at this - since we don't want to keep touching files outside of our modules, I'll make more changes so each controllers are in their own files.

**Comment by junsupark94** [comment]
@Lesson9 @itsjohnong @EtoKruto Check my latest commit and let me know what you think.

**Comment by itsjohnong** [comment]
@Lesson9 @junsupark94 @EtoKruto 
I think this works for me, it's modularized enough so we won't have as much collision in our code.

**Comment by EtoKruto** [comment]
@junsupark94 and team, this works for me as well. 

**Optional**: Later, if there is a need, we could also refactor any overarching GET commands under a 'shared' controller and then use specific controllers we have now for specific requests so its easier to have one source of truth. This is of course if we need to share gets across components.

Good to merge!

**Pull request merged**
